steps:
  - name: 'gcr.io/cloud-builders/npm'
    args: ['install']
  - name: 'alpine'
    entrypoint: 'echo'
    args: ['✅ Cloud Build ran successfully!']

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'
