steps:
  - name: 'gcr.io/cloud-builders/npm'
    args: ['install']
  - name: 'gcr.io/cloud-builders/npm'
    args: ['run', 'start']
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['run', 'deploy', 'cloud-build-demo', '--source=.', '--region=us-west2', '--platform=managed', '--allow-unauthenticated']

options:
  logging: CLOUD_LOGGING_ONLY
